apiVersion: v1
entries:
  oblivion-sentinel:
  - apiVersion: v2
    appVersion: 0.0.6
    created: "2025-10-10T10:38:28.101002694Z"
    description: Scan Kubernetes pods by health/time and apply a two-phase remediation,
      delete bad pods first, uninstall Helm releases later if degradation persists.
    digest: 0d850f773bc5b18f31ca5b8efa6d6c00693219410a44d22a04182ec6dfd708f8
    home: https://greybox.itblognote.com/helm/charts/oblivion-sentinel
    keywords:
    - cleanup
    - janitor
    - reaper
    - kubernetes
    - helm
    maintainers:
    - email: thanhphat@itblognote.com
      name: platform-team
    name: oblivion-sentinel
    type: application
    urls:
    - https://greybox.itblognote.com/helm/repo/oblivion-sentinel-0.0.10.tgz
    version: 0.0.10
generated: "2025-10-10T10:38:28.099235828Z"
